<?php
/**
 * Plugin Data Structure
 *
 * @package WordPress
 * @subpackage Multiple Products to Cart for WooCommerce
 * @since 1.0
 */

global $mpc__;

$mpc__           = array(
	'has_pro'       => false,
	'prostate'      => 'none',
	'prolink'       => 'https://webfixlab.com/plugins/multiple-products-to-cart-woocommerce-product-table/',
	'activate_link' => 'admin.php?page=mpc-shortcode-pricing',
	'plugin'        => array(
		'version'         => '7.0.2',
		'page_limit'      => 10,
		'screen'          => array(
			'toplevel_page_mpc-shortcodes',
			'multiple-products_page_mpc-shortcode',
			'multiple-products_page_mpc-settings',
			'multiple-products_page_mpca_license',
		),
		'review_link'     => 'https://wordpress.org/support/plugin/multiple-products-to-cart-for-woocommerce/reviews/?rate=5#new-post',
		'support'         => 'https://webfixlab.com/contact/',
		'request_quote'   => 'https://webfixlab.com/contact/',
		'docs'            => 'https://docs.webfixlab.com/kb/multiple-products-to-cart/',
		'woo_url'         => 'https://wordpress.org/plugins/woocommerce/',
		'free_mpc_url'    => 'https://wordpress.org/plugins/multiple-products-to-cart-for-woocommerce/',
		'shortcode_doc'   => 'https://docs.webfixlab.com/kb/multiple-products-to-cart/',
		'notice_interval' => 15, // days.
	),
	'notice'        => array(),
);
$mpc__['fields'] = array(
	'general-settings' => array(
		array(
			'section' => 'Redirect & Quantity',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'              => 'wmc_redirect',
					'type'             => 'radio',
					'options'          => array(
						'ajax'   => 'No-redirect',
						'cart'   => 'Cart',
						'custom' => 'Custom',
					),
					'default'          => 'ajax',
					'label'            => 'Redirect After Cart Addition',
					'desc'             => 'Choose the page to redirect customers to after they\'ve added products to their cart.',
					'followup'         => array(
						array(
							'key'         => 'mpca_custom_redirect',
							'type'        => 'text',
							'label'       => 'Custom Page URL',
							'placeholder' => 'https://webfixlab.com/contact/',
							'desc'        => 'Add a custom page URL where the customer should be redirected.',
						),
					),
					'followup_depends' => 'custom',
					'pro_label'        => 'Custom Redirect URL',
				),
				array(
					'key'         => 'wmca_default_quantity',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Initial Product Quantity',
					'desc'        => 'Set the starting value for the quantity field for each product.',
					'placeholder' => '0',
					'class'       => 'number-input',
				),
				array(
					'key'         => 'mpc_show_new_quantity_box',
					'type'        => 'checkbox',
					'label'       => 'Quantity Selector Design',
					'desc'        => 'Decide whether the quantity field should incorporate a plus-minus selector style.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
			),
		),
		array(
			'section' => 'Buttons',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmca_show_reset_btn',
					'type'        => 'checkbox',
					'label'       => 'Reset Button',
					'desc'        => 'Choose if a Reset button should accompany the Add to Cart button.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
				),
				array(
					'key'         => 'wmc_show_all_select',
					'type'        => 'checkbox',
					'label'       => 'Select All',
					'desc'        => 'Choose if a \'Select All\' checkbox should be added at the top right corner of the product table.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
				),
				array(
					'key'         => 'mpc_show_add_to_cart_button',
					'type'        => 'checkbox',
					'label'       => 'Add to Cart Button',
					'desc'        => 'Choose if you want to remove the Add to Cart button.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_add_to_cart_checkbox',
					'type'        => 'checkbox',
					'label'       => 'Checkbox',
					'desc'        => 'Choose if you want to remove the checkboxes from the product table, assuming customers will purchase all products from the current page of the product table.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
				array(
					'key'         => 'wmca_single_cart',
					'type'        => 'checkbox',
					'label'       => 'Individual \'Add to Cart\' Button',
					'desc'        => 'Decide if each product should have its own \'Add to Cart\' button.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
			),
		),
		array(
			'section' => 'Search & Fiilter',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmc_show_products_filter',
					'type'        => 'checkbox',
					'label'       => 'Product Sorting Dropdown',
					'desc'        => 'Choose if a product sorting dropdown should be displayed at the top of the product table.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
				),
				array(
					'key'         => 'mpc_show_title_dopdown',
					'type'        => 'checkbox',
					'label'       => 'Title Sorting Option',
					'desc'        => 'Choose if a \'Title\' option should be included in the sorting dropdown.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
				),
				array(
					'key'         => 'wmca_allow_sku_sort',
					'type'        => 'checkbox',
					'label'       => 'SKU Sorting Option',
					'desc'        => 'Choose if an \'SKU\' option should be included in the sorting dropdown.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_ajax_search',
					'type'        => 'checkbox',
					'label'       => 'Enable Ajax Search Box',
					'desc'        => 'Choose if an Ajax-powered search box should be added to the product table.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_ajax_cat_filter',
					'type'        => 'checkbox',
					'label'       => 'Category Filter Dropdown',
					'desc'        => 'Choose if a Category Filter dropdown should be displayed on the product table.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_cat_counter',
					'type'        => 'checkbox',
					'label'       => 'Show Product Count per Category',
					'desc'        => 'Choose if the number of products should be displayed beside each category name in the Category Filter Dropdown.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
			),
		),
		array(
			'section' => 'Others',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'mpc_show_variation_desc',
					'type'        => 'checkbox',
					'label'       => 'Variation Descriptions',
					'desc'        => 'Choose if product variation descriptions should dynamically showed based on variation selection.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
				),
				array(
					'key'         => 'wmc_show_pagination_text',
					'type'        => 'checkbox',
					'label'       => 'Display Pagination Text',
					'desc'        => 'Choose whether or not to display text like "Showing Products 1 - 10 / 75" above the pagination.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
				),
				array(
					'key'         => 'mpc_show_product_gallery',
					'type'        => 'checkbox',
					'label'       => 'Product Image Gallery',
					'desc'        => 'Choose to include additional product gallery images under the featured image in the product table.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_stock_out',
					'type'        => 'checkbox',
					'label'       => 'Display Out-of-Stock Products',
					'desc'        => 'Choose to include out-of-stock products in the table.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_subscription',
					'type'        => 'checkbox',
					'label'       => 'Support Subscription Products',
					'desc'        => 'Enable subscription product types.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
				array(
					'key'         => 'wmca_show_header',
					'type'        => 'checkbox',
					'label'       => 'Table Header',
					'desc'        => 'Choose whether to hide or display the table headers, which include the column titles.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_total_price',
					'type'        => 'checkbox',
					'label'       => 'Total Price',
					'desc'        => 'Choose whether the Total Price should be displayed.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_category_subheader',
					'type'        => 'checkbox',
					'label'       => 'Category-Based Subheadings',
					'desc'        => 'Enable the division of products into subsections based on their categories within the product table.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_show_on_sale',
					'type'        => 'checkbox',
					'label'       => 'Show \'Sale\' Label',
					'desc'        => 'Choose whether to add a \'Sale\' sticker to the featured product image.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
				),
			),
		),
	),
	'labels'           => array(
		array(
			'section' => 'Buttons',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmc_button_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Add to Cart',
					'desc'        => '',
					'placeholder' => 'Add to Cart',
				),
				array(
					'key'         => 'wmc_reset_button_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Reset',
					'desc'        => '',
					'placeholder' => 'Reset',
				),
				array(
					'key'         => 'mpce_single_order_button_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Single Add to Cart',
					'desc'        => '',
					'placeholder' => 'Add',
					'pro'         => true,
				),
			),
		),
		array(
			'section' => 'Table Column Titles',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmc_ct_image',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Image',
					'desc'        => '',
					'placeholder' => 'Image',
				),
				array(
					'key'         => 'wmc_ct_product',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Product',
					'desc'        => '',
					'placeholder' => 'Product',
				),
				array(
					'key'         => 'wmc_ct_price',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Price',
					'desc'        => '',
					'placeholder' => 'Price',
				),
				array(
					'key'         => 'wmc_ct_variation',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Variation',
					'desc'        => '',
					'placeholder' => 'Variation',
				),
				array(
					'key'         => 'wmc_ct_quantity',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Quantity',
					'desc'        => '',
					'placeholder' => 'Quantity',
				),
				array(
					'key'         => 'wmc_ct_buy',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Buy',
					'desc'        => '',
					'placeholder' => 'Buy',
				),
				array(
					'key'         => 'wmc_ct_category',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Category',
					'desc'        => '',
					'placeholder' => 'Category',
					'pro'         => true,
				),
				array(
					'key'         => 'wmc_ct_stock',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Stock',
					'desc'        => '',
					'placeholder' => 'Stock',
					'pro'         => true,
				),
				array(
					'key'         => 'wmc_ct_tag',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Tag',
					'desc'        => '',
					'placeholder' => 'Tag',
					'pro'         => true,
				),
				array(
					'key'         => 'wmc_ct_sku',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'SKU',
					'desc'        => '',
					'placeholder' => 'SKU',
					'pro'         => true,
				),
				array(
					'key'         => 'wmc_ct_rating',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Rating',
					'desc'        => '',
					'placeholder' => 'Rating',
					'pro'         => true,
				),
			),
		),
		array(
			'section' => 'Sorting Option',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'mpc_sddt_default',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Default sorting',
					'desc'        => '',
					'placeholder' => 'Default sorting',
				),
				array(
					'key'         => 'mpc_sddt_price_asc',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Price: Low to High',
					'desc'        => '',
					'placeholder' => 'Price: Low to High',
				),
				array(
					'key'         => 'mpc_sddt_price_desc',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Price: High to Low',
					'desc'        => '',
					'placeholder' => 'Price: High to Low',
				),
				array(
					'key'         => 'mpc_sddt_title_asc',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Title: A to Z',
					'desc'        => '',
					'placeholder' => 'Title: A to Z',
				),
				array(
					'key'         => 'mpc_sddt_title_desc',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Title: Z to A',
					'desc'        => '',
					'placeholder' => 'Title: Z to A',
				),
				array(
					'key'         => 'mpc_sddt_sku_asc',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'SKU: A to Z',
					'desc'        => '',
					'placeholder' => 'SKU: A to Z',
					'pro'         => true,
				),
				array(
					'key'         => 'mpc_sddt_sku_dessc',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'SKU: Z to A',
					'desc'        => '',
					'placeholder' => 'SKU: Z to A',
					'pro'         => true,
				),
			),
		),
		array(
			'section' => 'Others',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmc_total_button_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Total',
					'desc'        => '',
					'placeholder' => 'Total',
				),
				array(
					'key'         => 'wmc_pagination_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Pagination',
					'desc'        => '',
					'placeholder' => 'Showing Products',
				),
				array(
					'key'         => 'wmc_select_all_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Selelct All',
					'desc'        => '',
					'placeholder' => 'Selelct All',
				),
				array(
					'key'         => 'wmc_empty_value_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Empty Value',
					'desc'        => '',
					'placeholder' => 'N/A',
				),
				array(
					'key'         => 'wmc_option_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Prepend Placeholder Variation',
					'desc'        => '',
					'placeholder' => 'Default: Blank. Example: {Choose} Variation',
				),
			),
		),
		array(
			'section' => 'Error Notice',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'         => 'wmc_empty_form_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Product Not Selected',
					'desc'        => '',
					'placeholder' => 'Please check one or more products',
				),
				array(
					'key'         => 'wmc_missed_variation_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Variation Not Selected',
					'desc'        => '',
					'placeholder' => 'Please select all options',
				),
				array(
					'key'         => 'mpcp_empty_result_text',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Empty Search Result',
					'desc'        => '',
					'placeholder' => 'Sorry! No products found.',
					'pro'         => true,
				),
			),
		),
	),
	'appearence'       => array(
		array(
			'section' => 'Colors',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'     => 'wmc_thead_back_color',
					'type'    => 'color',
					'default' => '',
					'label'   => 'Header & Pagination Background',
					'desc'    => '',
				),
				array(
					'key'     => 'mpc_head_text_color',
					'type'    => 'color',
					'default' => '',
					'label'   => 'Header & Pagination Text',
					'desc'    => '',
				),
				array(
					'key'     => 'wmc_button_color',
					'type'    => 'color',
					'default' => '',
					'label'   => 'Cart Button Background',
					'desc'    => '',
				),
				array(
					'key'     => 'mpc_button_text_color',
					'type'    => 'color',
					'default' => '',
					'label'   => 'Cart Button Text',
					'desc'    => '',
				),
			),
		),
		array(
			'section' => 'Product Title Style',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'     => 'mpc_protitle_color',
					'type'    => 'color',
					'default' => '',
					'label'   => 'Color',
					'desc'    => '',
				),
				array(
					'key'         => 'mpc_protitle_font_size',
					'type'        => 'text',
					'default'     => '',
					'label'       => 'Font Size(px)',
					'desc'        => '',
					'placeholder' => '10',
					'min'         => 10,
					'max'         => 50,
					'class'       => 'number-input',
					'pro_label'   => 'Product Title Font Size',
				),
				array(
					'key'         => 'mpc_protitle_bold_font',
					'type'        => 'checkbox',
					'label'       => 'Bold',
					'desc'        => '',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro_label'   => 'Product Title Bold Font',
				),
				array(
					'key'         => 'mpc_protitle_underline',
					'type'        => 'checkbox',
					'label'       => 'Underline',
					'desc'        => '',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'pro_label'   => 'Product Title Underline',
				),
			),
		),
	),
	'new_table'        => array(
		array(
			'section' => 'Add New Product Table',
			'desc'    => '',
			'fields'  => array(
				array(
					'key'     => 'shortcode_title',
					'type'    => 'text',
					'label'   => 'Table Title',
					'desc'    => 'For internal use only, it helps admins identify the table and will not be shown to customers.',
					'placeholder' => 'Product table title',
				),
				array(
					'key'     => 'shortcode_desc',
					'type'    => 'text',
					'label'   => 'Table Description',
					'desc'    => 'For internal use only, it helps admins identify the table and will not be shown to customers.',
					'placeholder' => 'Description',
				),
				array(
					'key'          => 'ids',
					'type'         => 'selectbox',
					'label'        => 'Add Product',
					'desc'         => 'Select specific products to display if you want to add only certain items in the product table.',
					'content_type' => 'product',
					'multiple'     => true,
				),
				array(
					'key'          => 'selected',
					'type'         => 'selectbox',
					'label'        => 'Selected Products',
					'desc'         => 'Choose which products should be checked by default when the product table initially loads.',
					'content_type' => 'product',
					'multiple'     => true,
				),
				array(
					'key'          => 'cats',
					'type'         => 'selectbox',
					'label'        => 'Categories',
					'desc'         => 'Specify the product categories to be included in the product table.',
					'content_type' => 'product_cat',
					'multiple'     => true,
				),
				array(
					'key'     => 'limit',
					'type'    => 'text',
					'label'   => 'Products Per Page',
					'desc'    => 'Set a limit on the number of products to display per page. This option is functional only when the Pagination setting is Show. Maximum page limit is <strong style="font-weight:bold;">100.</strong>',
					'placeholder' => 10,
					'min'     => 1,
					'max'     => 50,
				),
				array(
					'key'         => 'pagination',
					'type'        => 'checkbox',
					'label'       => 'Pagination',
					'desc'        => 'If Hide is selected, all products will be shown on a single page without pagination.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'default'     => 'on',
				),
				array(
					'key'          => 'orderby',
					'type'         => 'selectbox',
					'label'        => 'Order By',
					'desc'         => 'Determine the attribute (like price, name, etc.) upon which the product sorting should be based.',
					'options'      => array(
						'date'  => 'Date',
						'title' => 'Title',
						'price' => 'Price',
						'id'    => 'ID',
						'sku'   => 'SKU',
					),
					'default'      => 'date',
					'content_type' => 'static',
					'multiple'     => false,
					'pro_options'  => array( 'id', 'sku' ),
				),
				array(
					'key'          => 'order',
					'type'         => 'selectbox',
					'label'        => 'Order',
					'desc'         => 'Define the display sequence as ascending, descending, or custom. The custom setting is functional only when you have pre-selected specific products in the Add Product section.',
					'options'      => array(
						'desc'   => 'DESC',
						'asc'    => 'ASC',
						'custom' => 'Custom',
					),
					'default'      => 'date',
					'content_type' => 'static',
					'multiple'     => false,
					'pro_options'  => array( 'custom' ),
				),
				array(
					'key'         => 'description',
					'type'        => 'checkbox',
					'label'       => 'Product Description',
					'desc'        => 'This is the individual product description.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'default'     => 'off',
				),
				array(
					'key'         => 'link',
					'type'        => 'checkbox',
					'label'       => 'Product Link',
					'desc'        => 'Choose whether or not product titles should link to their individual product pages.',
					'switch_text' => array(
						'on'  => 'Show',
						'off' => 'Hide',
					),
					'default'     => 'on',
				),
				array(
					'key'          => 'type',
					'type'         => 'selectbox',
					'label'        => 'Product Type',
					'desc'         => 'Select the types of products you wish to include in the product table.',
					'options'      => array(
						'all'                   => 'All',
						'simple'                => 'Simple',
						'variable'              => 'Variable',
						'subscription'          => 'Subscription',
						'variable-subscription' => 'Variable Subscription',
					),
					'default'      => 'all',
					'content_type' => 'static',
					'multiple'     => true,
					'pro_options'  => array( 'subscription', 'variable-subscription' ),
				),
			),
		),
	),
);

// hook to modify global $mpc__ data variable.
do_action( 'mpca_modify_core_data' );
